name: Build jobs

on:
  workflow_call:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container: ghcr.io/pgalonza/devkita64-atmosphere:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build sys-patch
        run: |
          make dist -j $(nproc)
          zip -r sys-patch.zip out
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sys-patch
          path: ./out
       - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.release_token }}
        file: ./sys-patch.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
