name: Build jobs

on:
  workflow_call:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container: ghcr.io/pgalonza/devkita64-atmosphere:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build sys-patch
        run: |
          git config --global --add safe.directory `pwd` 
          git submodule update --remote 
          make dist -j $(nproc)
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sys-patch
          path: ./out
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "./out"
