name: NX_CI

on:
  workflow_call:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
 
    container: devkitpro/devkita64

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-tags: true
        path: sys-patch
        submodules: recursive

    - name: Build sys-patch
      run: |
        make -C sys-patch -j$(nproc) dist && \
        VERSION=$(grep 'export VERSION := ' sys-patch/Makefile | cut -c 19-)
        TAGVERSION=$(curl -s https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest | grep "tag_name" | head -1 | cut -d '"' -f 4)
        echo "VERSION=${VERSION}" >> $GITHUB_ENV
        echo "TAGVERSION=${TAGVERSION}" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        include-hidden-files: true
        overwrite: true
        name: sys-patch-${{ env.VERSION }}
        path: sys-patch/out/
    - name: Upload zip to release
      uses: svenstaro/upload-release-action@master
      with:
        repo_token: ${{ secrets.release_token }}
        file: sys-patch/sys-patch.zip
        tag: ${{ github.ref }}
        file_glob: true
        overwrite: true
  
